### ISSUE TITLE
访问报错请问是什么问题？

### ISSUE THREAD

**Issue by starrysky90** [YufJi/tiny-v1#1]
![image](https://user-images.githubusercontent.com/12711203/226873237-d509da75-4429-4ba0-b019-054088f1f049.png)
服务起来后报这个，请教一下是什么原因

**Comment by YufJi** [comment]
哪个分支报错呢？可以看下示例目录下的.cache入口文件嘛

**Comment by starrysky90** [comment]
develop分支报错，.cache入口文件我明天截图给您， 您这边develop分支没问题吗？

**Comment by starrysky90** [comment]
![image](https://user-images.githubusercontent.com/12711203/227080714-84e945e5-a3c9-4981-8134-d70d364b54da.png)
![image](https://user-images.githubusercontent.com/12711203/227080772-4bee7dea-3a18-42a7-b61c-8ba2ccc37035.png)
![image](https://user-images.githubusercontent.com/12711203/227080795-c95bf8c4-9eb4-4336-b180-13cb472f98ba.png)

**Comment by YufJi** [comment]
看着是引用路径转错了😑， 很奇怪，我本地编译出来的是正常

**Comment by YufJi** [comment]
已修复
